### ISSUE TITLE
Format fails when method called "when" is present

### ISSUE THREAD

**Issue by doktorjw** [eclipse-jdt/eclipse.jdt#59] opened 2023-05-09 22:13 UTC
The following Java code will not format properly:

```
public class JunkClass {
    Object myObj;

    void foo() {
        when(myObj);
        foo(myObj);
        foo(myObj);
    }

    void foo( Object stuff ) {}
    void when( Object methodCall ) {}
}
```

We have the formatter configured to insert spaces after the open parenthesis, and before the close parenthesis of method invocations. Selecting all the code and formatting it, the "when(myObj)" and subsequent function invocations are not formatted. 

However, changing the order of invocation to:

```
    void foo() {
        foo(myObj);
        when(myObj);
        foo(myObj);
    }
```

will result in the code being formatted properly.

We found, too, that if you change the "when" method name to "whenx", then the formatting is correct.

We stumbled across this while investigating why a JUnit test class wouldn't format with Mockito "when" statements within it.

What is also interesting is that the formatting failure seems to be method specific. If you add a "foo2" method such that you have one formatted the "good" way and one the "bad" way (ordering of the method calls), one method will successfully format, and the other will not.

Very strange, and very unexpected.

I am running eclipse on a Linux Ubuntu 22.04 install:

os.arch=amd64
os.name=Linux
os.version=5.15.0-71-generic
osgi.arch=x86_64

with a very recent version of the eclipse JDT (just updated today):

Version: 3.19.0.v20230302-0300
Build id: I20230302-0300

We also verified this behavior with:

Version: 3.18.1400.v20221123-1800
Build id: I20221123-1800

We are configured to use jdk 11.

dr_j

**Comment by Madjosz** [comment] 2023-06-01 09:41
Duplicate of https://github.com/eclipse-jdt/eclipse.jdt.core/issues/609

**Comment by srikanth-sankaran** [comment] 2023-10-02 01:56
The PR https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1436 fixes this problem and includes the test snippet from here as regression test. Closing ...

**Closed by srikanth-sankaran** 2023-10-02 01:56 UTC
